---
# Create certs directory
- name: Create Nomad TLS directory
  file:
    path: "{{ nomad_config_dir }}/certs"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
    state: directory

  - name: Donwload Certs
    get_url:
      url: "{{ nomad_certs_url }}"
      dest: "{{ nomad_fetch_dir }}/certs.zip"
      force: no

  - name: Unzip Certs
    unarchive:
      src: "{{ nomad_fetch_dir }}/certs.zip"
      dest: "{{ nomad_config_dir }}"
      remote_src: yes

- name: Set CA file
  set_fact:
    tls_ca_file: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"

- name: Set NOMAD_CACERT environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CACERT={{ tls_ca_file }}"

- name: Set NOMAD_CLIENT_CERT environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CLIENT_CERT={{ nomad_config_dir }}/certs/global-cli-nomad.pem"

- name: Set NOMAD_CLIENT_KEY environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CLIENT_KEY={{ nomad_config_dir }}/certs/global-cli-nomad-key.pem"

- name: Set cert files
  set_fact:
    tls_cert_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
    tls_key_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad-key.pem"
  when: server_enabled

- name: Set cert files
  set_fact:
    tls_cert_file: "{{ nomad_config_dir }}/certs/global-client-nomad.pem"
    tls_key_file: "{{ nomad_config_dir }}/certs/global-client-nomad-key.pem"
  when: client_enabled

- name: Slurp acl_bootstrap file
  slurp:
    src: "{{ nomad_config_dir }}/certs/acl_bootstrap"
  register: acl_bootstrap_file

- name: Get Bootstrap Token
  set_fact:
    NOMAD_TOKEN: "{{ acl_bootstrap_file['content'] | b64decode | regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'Secret ID\s+=\s+(.*)'

- name: nomad_secret_id
  debug:
    msg: "{{ NOMAD_TOKEN }}"

- name: Set NOMAD_TOKEN environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_TOKEN={{ NOMAD_TOKEN }}"
