---
- name: Include "{{ansible_os_family}}" Nomad recipe
  include: "{{ansible_os_family}}.yaml"
  
- name: Download nomad files
  get_url: url=https://releases.hashicorp.com/nomad/0.6.3/nomad_0.6.3_linux_amd64.zip dest=/tmp/nomad_0.6.3_linux_amd64.zip
  register: result
  until: result|success
  retries: 5
  delay: 1

- name: Decompress files
  file: path=/tmp/nomad state=directory
- unarchive: src=/tmp/nomad_0.6.3_linux_amd64.zip dest=/tmp/nomad copy=no creates=/tmp/nomad/nomad

- name: Include "{{nomad_type_of_node}}" nomad recipe
  include: "{{nomad_type_of_node}}.yml"
