---
# Generate CA Cert
- import_tasks: tls_ca.yml

# Generate CLI Cert
- import_tasks: tls_cli.yml

# Generate Server Cert
- import_tasks: tls_server.yml
  when: server_enabled

# Generate Client Cert
- import_tasks: tls_client.yml
  when: client_enabled
