---
- name: Create Nomad TLS directory
  file:
    path: "{{ nomad_config_dir }}/certs"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
    state: directory

- name: Create Nomad TLS CA
  command: nomad tls ca create
  args:
    chdir: "{{ nomad_config_dir }}/certs"
    creates: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"
  when: ansible_connection == 'local'

- name: Wait CA Cert to be generated
  wait_for:
    path: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"
  delegate_to: localhost

- name: Copy CA to the nodes
  copy:
    src: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"
    dest: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"

- name: Set CA file
  set_fact:
    tls_ca_file: "{{ nomad_config_dir }}/certs/nomad-agent-ca.pem"

- name: Set NOMAD_CACERT environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CACERT={{ tls_ca_file }}"

- block:

  - name: Create Nomad TLS Server Cert
    command: nomad tls cert create -server -cluster-region {{ nomad_region }} -additional-dnsname={{ tls_dns_name }} -additional-ipaddress={{ tls_private_ip }} -additional-ipaddress={{ tls_public_ip }}
    args:
      chdir: "{{ nomad_config_dir }}/certs"
      creates: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
    delegate_to: localhost
  
  - name: Copy Server Cert to the nodes
    copy:
      src: "{{ item }}"
      dest: "{{ item }}"
    loop:
    - "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
    - "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad-key.pem"

  - name: Set cert files
    set_fact:
      tls_cert_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
      tls_key_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad-key.pem"

  when: server_enabled

- name: Create Nomad TLS CLI Cert
  command: nomad tls cert create -cli
  args:
    chdir: "{{ nomad_config_dir }}/certs"
    creates: "{{ nomad_config_dir }}/certs/global-cli-nomad.pem"
  delegate_to: localhost

- name: Copy client Cert to the nodes
  copy:
    src: "{{ item }}"
    dest: "{{ item }}"
  loop:
  - "{{ nomad_config_dir }}/certs/global-cli-nomad.pem"
  - "{{ nomad_config_dir }}/certs/global-cli-nomad-key.pem"

- name: Set NOMAD_CLIENT_CERT environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CLIENT_CERT={{ nomad_config_dir }}/certs/global-cli-nomad.pem"

- name: Set NOMAD_CLIENT_KEY environment variable
  lineinfile:
    dest: /etc/environment
    line: "NOMAD_CLIENT_KEY={{ nomad_config_dir }}/certs/global-cli-nomad-key.pem"

- block:

  - name: Create Nomad TLS client Cert
    command: nomad tls cert create -client -additional-dnsname={{ tls_dns_name }} -additional-ipaddress={{ tls_private_ip }} -additional-ipaddress={{ tls_public_ip }}
    args:
      chdir: "{{ nomad_config_dir }}/certs"
      creates: "{{ nomad_config_dir }}/certs/global-client-nomad.pem"
    delegate_to: localhost

  - name: Copy client Cert to the nodes
    copy:
      src: "{{ item }}"
      dest: "{{ item }}"
    loop:
    - "{{ nomad_config_dir }}/certs/global-client-nomad.pem"
    - "{{ nomad_config_dir }}/certs/global-client-nomad-key.pem"

  - name: Set cert files
    set_fact:
      tls_cert_file: "{{ nomad_config_dir }}/certs/global-client-nomad.pem"
      tls_key_file: "{{ nomad_config_dir }}/certs/global-client-nomad-key.pem"

  when: client_enabled

- name: Set correct permissions in Nomad TLS directory
  file:
    path: "{{ nomad_config_dir }}/certs"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    state: directory
    recurse: yes