---
# Generate Server Cert
- when: nomad_master
  block:

  - name: Create Nomad TLS Server Cert
    command: nomad tls cert create -server -cluster-region {{ nomad_region }} -additional-dnsname={{ tls_dns_name }} -additional-ipaddress={{ tls_private_ip }} -additional-ipaddress={{ tls_public_ip }} -ca {{ nomad_config_dir }}/certs/nomad-agent-ca.pem -key {{ nomad_config_dir }}/certs/nomad-agent-ca-key.pem
    args:
      chdir: "{{ nomad_config_dir }}/certs/"
      creates: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
    become_user: "{{ nomad_user }}"

  - name: "Fetch Server cert from nomad-master to ansible-master"
    fetch:
      src: "{{ nomad_config_dir }}/certs/{{ item }}"
      dest: "{{ nomad_fetch_dir }}/{{ item }}"
      flat: yes
    loop:
    - "{{ nomad_region }}-server-nomad.pem"
    - "{{ nomad_region }}-server-nomad-key.pem"

- when: server_enabled
  block:

  - name: Wait Server Cert to be generated
    wait_for:
      path: "{{ nomad_fetch_dir }}/{{ nomad_region }}-server-nomad.pem"
    delegate_to: localhost

  - name: Copy Server Cert to the nodes
    copy:
      src: "{{ nomad_fetch_dir }}/{{ item }}"
      dest: "{{ nomad_config_dir }}/certs/{{ item }}"
    loop:
    - "{{ nomad_region }}-server-nomad.pem"
    - "{{ nomad_region }}-server-nomad-key.pem"

  - name: Set cert files
    set_fact:
      tls_cert_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad.pem"
      tls_key_file: "{{ nomad_config_dir }}/certs/{{ nomad_region }}-server-nomad-key.pem"
