---
- name: Create client config file
  copy:
    dest: "/tmp/client.hcl"
    src: "client.hcl"
    mode: 0644

- name: Modify client config
  lineinfile: 
     dest: "/tmp/client.hcl"
     line: "servers = {{ nomad_server_ip }}"
     regexp: "^servers ="
     state: present

- name: Start nomad daemon
  command: /tmp/nomad agent -client -config /tmp/client.hcl
  async: 1000
  poll: 0

